### PR TITLE
feat: style overrides

### PR DESCRIPTION
**Pull request by deer**
closes https://github.com/deer/fresh_blog/issues/12

@scottyg, what do you think of this? If you go into `tests/styles_fixture` you can run `deno task start` to start the test project. If you open the developer console (I'm assuming chrome -- otherwise you're on your own!) and then do "cmd shift p" followed by searching for "show rendering", you can eventually find a spot where it says "Emulate CSS media feature prefers-color-scheme". This lets you switch between the user's default, forced light, and forced dark.

In the sample project you can see that I've configured the markdown style (via the blog config) to be "auto", i.e. the user's default. Then I've also provided two separate styles in the twind config to demonstrate light and dark. Please let me know if you need more control over things. I guess I can always add more twind class names that can then be overridden in the user's twind config.

### CODE REVIEW

**Comment by scottyg** [comment]
@deer I like where this is heading. I think the only thing that would be nice would be to allow you to change the class names for <main>, use case would be if someone wanted to have a side bar or have a full width template. Eventually I'd love to embed the PostList into other page templates. But this change is a step in the right direction!

**Comment by deer** [comment]
Great, thanks for the feedback. I've been busy learning more about tailwind, since I was just hacking things around without understanding the fundamentals. I have a much better sense of what's going on now, and I hope to do everything much better with the next commit. Hopefully that's tomorrow, but who knows.

Note: this is something of a moving target, since there's an effort underway to switch fresh from twind to uno: https://github.com/denoland/fresh/pull/1303.

Can you please log an issue with some thoughts on exporting PostList? In particular, please clarify your use case / motivation. And if you can imagine needing other things in the future, might as well include that for completeness as well. (Just to help me understand how people plan on using this.)

**Comment by deer** [comment]
Additionally I should mention that the fresh documentation customizes the default https://github.com/denoland/deno-gfm. They do this by [linking](https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/www/routes/docs/%5B...slug%5D.tsx#L149) to a route that produces a stylesheet. This sheet is defined [here](https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/www/routes/gfm.css.ts). This is a nice approach that allows for further customization of the markdown body. I plan on doing this at some point in order to get the markdown to properly behave as well.

**Comment by scottyg** [comment]
I feel like this is a good start but maybe we should hold off on styling until the proposed move to uno that you mentioned?

**Comment by deer** [comment]
Agree, looks like they/re making good progress on the above mentioned PR.

**Comment by deer** [comment]
Creating a new PR very soon, because this one is too outdated.

**Pull request closed without merging**
